language: python

install:
  - npm install -g bower
  - pip install tox

script:
  - tox

env:
  - TOXENV=django17-py27
  - TOXENV=django17-py34
  - TOXENV=django18-py27
  - TOXENV=django18-py34

matrix:
  allow_failures:
    - TOXENV=django17-py34
    - TOXENV=django18-py34
  fast_finish: true
