django:
  command: entrypoint.sh runtests.sh
  environment:
    TRAVIS:
    TRAVIS_BRANCH:
    TRAVIS_JOB_ID:
  image: interaction/icekit:${TAG}
  links:
    - elasticsearch
    - postgres
    - redis
  volumes:
    - ./.git:/opt/django-icekit/.git
    - ./project_template/var:/opt/django-icekit/project_template/var
elasticsearch:
  image: interaction/elasticsearch-icu:1
postgres:
  image: onjin/alpine-postgres:9.4
redis:
  command: redis-server --appendonly yes
  image: redis:3-alpine
