django:
  command: entrypoint.sh runtests.sh
  environment:
    PGHOST: postgres
    PGUSER: postgres
    TRAVIS:
    TRAVIS_BRANCH:
    TRAVIS_JOB_ID:
  image: interaction/icekit:latest
  links:
    - elasticsearch
    - postgres
    - redis
  volumes:
    - ./.git:/opt/django-icekit/.git
    - ./icekit-project/var:/opt/django-icekit/icekit-project/var
elasticsearch:
  image: interaction/elasticsearch-icu:1
postgres:
  image: onjin/alpine-postgres:9.4
redis:
  command: redis-server --appendonly yes
  image: redis:3-alpine
