django:
  command: runtests.sh
  environment:
    QUICK: 1
    TRAVIS: # Get from environment
    TRAVIS_BRANCH: # Get from environment
    TRAVIS_JOB_ID: # Get from environment
  image: interaction/project_template:${TAG}
  links:
    - elasticsearch
    - postgres
    - redis
  volumes:
    - ./.git:/opt/project_template/.git
    - ./var:/opt/project_template/var
elasticsearch:
  image: interaction/elasticsearch-icu:1-alpine
postgres:
  image: postgres:9.4-alpine
redis:
  command: redis-server --appendonly yes
  image: redis:3-alpine
