version: "2"
services:
  celery:
    links:
      - elasticsearch
      - postgres
      - redis
  celerybeat:
    links:
      - redis
  celeryflower:
    links:
      - redis
    ports:
      - 5555:5555
  django:
    build: .
    links:
      - elasticsearch
      - celery
      - redis
    ports:
      - 8000:8000
  # elasticsearch:
  #   ports:
  #     - 9200
  postgres:
    ports:
      - 5432
  redis:
    ports:
      - 6379
