version: "2"
services:
  celery:
    command: setup-django.sh celery.sh
    extends: django
  celerybeat:
    command: setup-django.sh celerybeat.sh
    extends: django
  celeryflower:
    command: setup-django.sh celeryflower.sh
    extends: django
  django:
    command: setup-django.sh runserver.sh
    environment:
      BASE_SETTINGS_MODULE: develop
      TERM: # Get from environment
    image: interaction/project_template:latest
    tmpfs:
      - /tmp
    volumes:
      - ./:/opt/project_template
  elasticsearch:
    image: interaction/elasticsearch-icu:1
  postgres:
    image: onjin/alpine-postgres:9.4
  redis:
    command: redis-server --appendonly yes
    image: redis:3-alpine
