version: "2"
services:
  base:
    env_file: .env.local
    environment:
      BASE_SETTINGS_MODULE: develop
      GPG_PASSPHRASE: # Get from environment
      MASTER_PASSWORD: # Get from environment
      TERM: # Get from environment
    image: interaction/project_template:local
    tmpfs:
      - /tmp
    volumes:
      - ./:/opt/project_template
  celery:
    command: setup-django.sh celery.sh
    extends: base
    links:
      - elasticsearch
      - postgres
      - redis
  celerybeat:
    command: setup-django.sh celerybeat.sh
    extends: base
    links:
      - redis
  celeryflower:
    command: setup-django.sh celeryflower.sh
    expose:
      - 5555
    extends: base
    links:
      - redis
  django:
    build: .
    command: setup-django.sh bash.sh
    extends: base
    links:
      - celery
      - celerybeat
      - celeryflower
      - elasticsearch
      - postgres
      - redis
    ports:
      - 8000:8000
  elasticsearch:
    expose:
      - 9200
    image: interaction/elasticsearch-icu:1
  postgres:
    expose:
      - 5432
    image: onjin/alpine-postgres:9.4
  redis:
    command: redis-server --appendonly yes
    expose:
      - 6379
    image: redis:3-alpine
